import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import { Trans, useTranslation } from 'react-i18next';
export default function Home() {
  let [t,i18n]=useTranslation();
 function languageHandler(lang){
  
 i18n.changeLanguage(lang)
  }
  return (
    <div className={`${styles.container} ${i18n.language==='ar' ? styles.rtl : styles.ltr  }`  }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.buttons}>
        <button  onClick={()=>languageHandler('ar')}><Trans>Arabic</Trans> </button>
          <button  onClick={()=>languageHandler('en')} ><Trans>English</Trans></button>
        </div>
          
       
        <h1 className={styles.title}>
          <Trans>Welcome to</Trans> <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <Trans>Get started by editing</Trans>{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2><Trans>Documentation</Trans>  </h2>
            <p><Trans>Find in-depth information about Next.js features and API.</Trans>  </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2><Trans>Learn</Trans>  </h2>
            <p><Trans>Learn about Next.js in an interactive course with quizzes!</Trans> </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2><Trans>Examples</Trans>  </h2>
            <p><Trans>Discover and deploy boilerplate example Next.js projects.</Trans></p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2><Trans>Deploy</Trans>  </h2>
            <p>
            <Trans>Instantly deploy your Next.js site to a public URL with Vercel.</Trans>
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
